name: Deploy Next.js to VPS

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and Push Docker Image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: sithiraps/sithira-me:latest
    - name: Deploy on VPS via SSH
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        port: 22
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        script: |
          docker stop sithira-me || true
          docker rm sithira-me || true
          docker run -d --pull=always --restart=unless-stopped --name sithira-me \
            --network my-proxy-network \
            -p 4020:4020 \
            -e NODE_ENV=production \
            -e GA_ID=${{ secrets.GA_ID }} \
            sithiraps/sithira-me:latest
