name: Deploy Next.js to VPS

on:
  push:
    branches: [ "main" ]  # or "master" if that's your branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and Push Docker Image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: sithiraps/sithira-me:latest
        cache-from: type=registry,ref=sithiraps/sithira-me:cache
        cache-to: type=registry,ref=sithiraps/sithira-me:cache,mode=max

    - name: Deploy on VPS via SSH
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        script: |
          docker stop sithira-me || true
          docker rm sithira-me || true
          docker run -d --pull=always --name sithira-me \
            --network shared-web-network \
            -p 4355:4255 \
            -e NODE_ENV=production \
            -e NEXT_PUBLIC_GA_ID=${{ secrets.NEXT_PUBLIC_GA_ID }} \
            sithiraps/sithira-me:latest
